[workspace]
members = [
    "fvm",
    "sdk",
    "shared",
    "testing/*",
    "ipld/*",
]

[profile.actor]
inherits = "release"
panic = "abort"
overflow-checks = true
lto = true
opt-level = "z"
#strip = true
