[package]
name = "fvm_integration_tests"
description = "Filecoin Virtual Machine conformance tests"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/filecoin-project/ref-fvm"

[dependencies]
fvm = { version = "0.5.1", path = "../../fvm", default-features = false }
fvm_shared = { version = "0.5.1", path = "../../shared" }
fvm_ipld_hamt = { version = "0.4.0", path = "../../ipld/hamt"}
fvm_ipld_amt = { version = "0.4.0", path = "../../ipld/amt"}
fvm_ipld_car = { version = "0.4.0", path = "../../ipld/car" }

actors-v6 = { version = "6.0.5", package = "fil_builtin_actors_bundle" }
actors-v7 = { version = "7.0.4", package = "fil_builtin_actors_bundle" }
anyhow = "1.0.47"
cid = { version = "0.8.2", default-features = false }
futures = "0.3.19"
multihash = { version = "0.16.1", default-features = false }
num-traits = "0.2"
lazy_static = "1.4.0"
libsecp256k1 = "0.7.0"
rand = "0.8.5"
rand_chacha = "0.3"
thiserror = "1.0.30"
wasmtime = "0.33.0"

[dev-dependencies]
wabt = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
