[package]
name = "fuel-est"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0"

[dependencies.wasmtime]
version = "0.35.2"
default-features = false
features = ["cranelift", "pooling-allocator", "parallel-compilation"]

[dependencies.fvm]
path = "../../fvm"